[project]
name = "testcaserunner"
version = "0.2.0"
dependencies = [
    "numpy",
    "Jinja2",
    "matplotlib",
    "pandas",
    "seaborn",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = [
    "*.j2",
    "*.css",
    "*.js",
]
