# tox.ini
[tox]
envlist = integration, mypy

[testenv]
deps = -r requirements.txt

; [testenv:unit]
; changedir = tests/unit_tests
; commands = pytest -v

[testenv:integration]
changedir = tests
commands = pytest -v

[testenv:mypy]
commands = mypy src/testcaserunner/
