name: pytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd tests
          set -o pipefail
          python -m pytest --junitxml=pytest.xml --cov-report=term-missing --cov=../src | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@v1.1.47
        with:
          pytest-coverage-path: tests/pytest-coverage.txt
          junitxml-path: tests/pytest.xml
